FROM node:8

ENV RELEASE_URL https://github.com/OWASP/NodeGoat/archive/master.zip
ENV RELEASE_DIR NodeGoat-master

ADD ./development.js /app/development.js

WORKDIR /app

RUN \
  echo "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main" > /etc/apt/sources.list && \
  apt-get update && \
  apt-get -y install bash bash-doc bash-completion curl wget unzip mongodb && \
  mkdir -p /data/db && \
  cd /app && wget "${RELEASE_URL}" -O nodegoat.zip && \
  unzip nodegoat.zip && \ 
  rm nodegoat.zip && \
  cp /app/development.js /app/${RELEASE_DIR}/config/env && \
  cd ${RELEASE_DIR} && \
  npm install 

COPY ./start-server.sh /app/${RELEASE_DIR}/start-server.sh
COPY ./server.js /app/${RELEASE_DIR}/server.js

WORKDIR /app/${RELEASE_DIR}

EXPOSE 4000

CMD ["./start-server.sh"]

